version: '3'

# docker-compose build; docker-compose up -d docker-compose.yaml
# Then check the logs with
# docker logs --tail 50 $service_namee
# docker-compose images
# docker-compose logs --tail 20 service_namee

services:
  mongo:
    image: mongo
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - recipes-net
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  dev:
    container_name: dev
    environment:
      MONGO_APP_USERNAME: cook
      MONGO_APP_PASSWORD: bottlewasher
    volumes:
      - .:/opt/app-root/src/recipe-crawler
      - ../recipe-scrapers:/opt/app-root/src/recipe-scrapers
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - mongo
    networks:
      - recipes-net
    entrypoint:
      /opt/app-root/src/recipe-crawler/crawler_start.sh
    links:
      - mongo

  prod:
    container_name: crawler
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - mongo
    networks:
      - recipes-net
#    volumes:
#      - ./:/opt/app-root/src/app
    command:
      python3 -c 'import sys; print("\n".join(sys.modules))' >> /tmp/python_mods.log
    links:
      - mongo

networks:
  recipes-net:
    driver: bridge
